# Generated by Django 4.2.6 on 2023-11-19 10:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RutaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_inicial', models.CharField(max_length=300)),
                ('ubicacion_final', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_plazas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('creador', models.CharField(max_length=128)),
                ('participantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
    ]
