# Generated by Django 4.2.6 on 2023-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser_sender', models.CharField(default=None, max_length=128, null=True)),
                ('idUser_reciever', models.CharField(default=None, max_length=128, null=True)),
                ('room_name', models.CharField(max_length=100)),
                ('last_conection', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('creator', models.BooleanField()),
                ('id_chat', models.CharField(default=None, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('room_name', models.CharField(max_length=100)),
            ],
        ),
    ]
