# Generated by Django 4.2.6 on 2023-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(default=None, max_length=128, null=True, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('last_conection', models.DateTimeField()),
            ],
        ),
    ]
