# Generated by Django 4.2.6 on 2023-11-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_conection',
            field=models.IntegerField(),
        ),
    ]
