# Generated by Django 4.2.6 on 2023-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0002_chargerlocation_charger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerFullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('ac_dc', models.CharField(max_length=100)),
                ('acces', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('province_code', models.CharField(max_length=100)),
                ('mun', models.CharField(max_length=100)),
                ('charger_speed', models.CharField(max_length=100)),
                ('conection_type', models.CharField(max_length=200)),
            ],
        ),
    ]
